### ISSUE TITLE
No double dots or dots at begin or end of name part should be allowed in strict mode

### ISSUE THREAD

**Issue by Envek** [balexand/email_validator#26]
As said on the page http://www.remote.org/jochen/mail/info/chars.html (strict validator is based on it as said in README):

> [Dots are] allowed in email addresses. Often used for addresses with the format 'firstname.lastname@example.com'. There is one restriction however: **Two dots next to each other or a dot at the beginning or end of the local part are not allowed by RFC2822**. The reason is that in RFC2822 the dot is used as a separator for tokenizing the mail address. Dots at the named locations would mean an empty token, which is not allowed. Still, there are people who use it. Some MTAs accept it, some don't.

But currently such emails are treat as good:

```
> EmailValidator.regexp(strict_mode: true) =~ 'bad.email.@gmail.com'
# => 0
```

And I see a lot of `Net::SMTPError: bad address` errors in log when trying to send emails. I filtering emails from user input with strict mode.

I think taht such emails should be forbidden in strict mode. What do you think?

**Comment by balexand** [comment]
I've gotten rid of strict mode in version 2.0.0 of this gem. See #49 and the new README. Thanks!
