### ISSUE TITLE
Active Model referenced but not required?

### ISSUE THREAD

**Issue by RyanEdwardHall** [balexand/email_validator#28]
In line 2 where you define EmailValidator as a subclass of ActiveModel, I get an error "uninitialized constant ActiveModel (NameError)" - I have a very lean application and removed ActiveModel from the project. I think this is working for other people because it's using the ActiveModel that other gems have required. Just doing a `require 'active_model'` before the class definition should fix this.

**Comment by balexand** [comment]
Thanks @RyanEdwardHall, and sorry for the 4 year delay 😬 💖
