### ISSUE TITLE
test＿test@example.com should fail?

### ISSUE THREAD

**Issue by matsubo** [balexand/email_validator#34]
I found `test＿test@example.com` passes the validation. The email has multi-byte underbar before the at-mark.

(The validation fails if I set strict mode)

AWS SES rejected the email address so I wonder what is the expected result.

**Comment by karlwilbur** [comment]
I t depends on the RFC to which validation conforms. RFC 822 does not allow multibyte characters.

**Comment by balexand** [comment]
After #49 the validation is intentionally left loose. That email will pass validation. See #49 and the new README for details.

@karlwilbur Thanks for all of the comments you've made in the issues and pull-request here ❤️

**Comment by matsubo** [comment]
I want this gem implements RFC validation rule and be selectable from option.
v2 does not validate email address anymore... 

> `/[^\s]@[^\s]/`.
https://github.com/balexand/email_validator/blob/3f9628baad1761253a4ebd843815750e1523d314/lib/email_validator.rb#L13

**Comment by karlwilbur** [comment]
@balexand, Happy to help.
