### ISSUE TITLE
Option to not allow UTF8 addresses

### ISSUE THREAD

**Issue by dbackeus** [balexand/email_validator#35]
Since the `mail` gem used by `ActionMailer` etc doesn't support UTF8 addresses (https://github.com/mikel/mail/issues/1014) could be nice have them invalidated.

**Comment by travisbell** [comment]
Just adding a vote for this as well. I use Amazon SES for all of my emailing and SES (apparently) adheres to RFC 5322 and 5321 which does not allow any alpha characters but [A-Za-z]. I've monkey patched the regex for my local usage but it would be nice to have a setting to make it more broadly available.

My reference for SES: https://forums.aws.amazon.com/thread.jspa?threadID=210804

**Comment by balexand** [comment]
I'm moving to a looser validation in version 2.0. See #49 and the new README for an explanation. If you need stricter validation then I suggest using a different gem. If there's one you like then open an issue here to let me know and I'll link to it in the README. Thanks!
