### ISSUE TITLE
Trailing and leading whitespace in email should not be valid

### ISSUE THREAD

**Issue by flivni** [balexand/email_validator#40]
Currently the regex allows trailing and leading whitespace. e.g. "\nfoo@bar.com\n " is allowed. Is this on purpose? The mail servers I use reject such emails.

**Comment by karlwilbur** [comment]
I believe that this is correct and expected behavior in the "loose" normal validation. It should not be valid in strict mode.

**Comment by balexand** [comment]
I think your best bet here to to automatically trim the whitespace. See https://github.com/balexand/email_validator/pull/31#issuecomment-165557819

Also, the validation is intentionally loose. See #49 and the new README.
