### ISSUE TITLE
Shouldn't test.1#@mailinator.com fail ?

### ISSUE THREAD

**Issue by kushagr** [balexand/email_validator#42]
Hey, I am using email_validator in my application and according to the documentation , '#' isn't allowed in strict mode. Somehow though test.1#@mailinator.com passes the validation.

**Comment by rdeavila** [comment]
In my setup, `test.1#@mailinator.com` don't pass using `strict_mode: true`.

**Comment by balexand** [comment]
Thanks. The validation is intentionally loose. See #49 and the new README.
