### ISSUE TITLE
False positive email validations

### ISSUE THREAD

**Issue by chrisokamoto** [balexand/email_validator#53]
After I updated from version 1.6.0 to 2.0.1 I got some false positives on the email validation. I have a test on my application that doesn't let an object with an invalid email be saved. 
Previously with the version 1.6.0 the tests were running as expected (object wasn't being created). The email that I use for this test is "b@man".
But now, the version 2.0.1 says this is a valid email, which makes my test fails and also, this is not a valid email, so this is an issue with the gem. 

I did some other tests and these are the results:
_Version 1.6.0_
[STAG]US:(ec)[1] pry(main)> EmailValidator.valid?('b@man')
=> false
[STAG]US:(ec)[2] pry(main)> EmailValidator.valid?('email@domain@domain.com')
=> false

_Version 2.0.1_
USOps:(ec)[31] pry(main)> EmailValidator.valid?('b@man')
=> true
USOps:(ec)[32] pry(main)> EmailValidator.valid?('email@domain@domain.com')
=> true

**Comment by chrisokamoto** [comment]
Oh I just read that you're using a loose validation now that just checks the occurency of [something]@[something] :(

**Comment by matsubo** [comment]
This gem does not validate email address anymore.
https://github.com/balexand/email_validator/issues/34#issuecomment-481083370
