### ISSUE TITLE
Validation not catching jdoe@example-com

### ISSUE THREAD

**Issue by SaimonL** [balexand/email_validator#59]
Validation not catching 

* jdoe@example-com
* jdoe@examplecom
* jdoe@example_com

**Comment by karlwilbur** [comment]
This is expected behavior. Please read the 'Validation philosophy" section of the README.

You can also see more detail in my comment on #58.

**Comment by SaimonL** [comment]
Reading http://www.dns-sd.org/trailingdotsindomainnames.html I have realized that you can send an email to a local host that do not have any dot in the domain name. The dot is not necessary unless you want a "Fully-Qualified Domain" email to be sent.

**Comment by karlwilbur** [comment]
@SaimonL You can also send an email to a local user in which case the local host is inferred. Thus `karl` is a valid email address and the `@` isn't strictly needed either. I do this several times a year myself.
